const STORAGE_KEY = 'lift-log-v1';
const seedWorkouts = [
  {date:'2026-07-28', exercises:[['Bench press',125,'9, 9, 9'],['Barbell squats',155,'8, 8, 8'],['Dumbbell overhead press',40,'8, 8, 6'],['Stiff-leg deadlift',145,'10, 10, 10'],['Seated flies',150,'10, 10, 8'],['Triceps overhead cable pull',32.5,'10, 10, 10'],['Dumbbell bicep curls',30,'8, 8, 8'],['Leg raises',null,'10, 10']]},
  {date:'2026-07-20', exercises:[['Barbell overhead press',85,'8, 8, 8'],['Split squats',35,'8, 8, 8'],['Seated rows',125,'6, 6'],['Cable flies',160,'8, 8, 8'],['Stiff-leg deadlift',140,'10, 10, 10'],['Triceps overhead cable pull',30,'8, 8, 8']]},
  {date:'2026-07-16', exercises:[['Assisted pull-ups',31.25,'8, 8, 8'],['Barbell squats',150,'8, 8, 8'],['Bench press',125,'9, 8, 5'],['Cable single-arm row',100,'10, 10, 10'],['Dumbbell overhead press',40,'10, 8, 7'],['Seated flies',150,'10, 8']]},
  {date:'2026-07-10', exercises:[['Dumbbell overhead press',40,'8, 8, 8'],['Stiff-leg deadlift',135,'10, 10, 10'],['Cable chest flies',180,'10, 10, 10'],['Tricep cable pulldown',42.5,'10, 10, 10'],['Walking lunges',60,'10, 10, 10'],['Lat pulldown',120,'10, 10, 10']]},
  {date:'2026-07-06', exercises:[['Assisted pull-ups',37.5,'10, 10, 7'],['Bench press',125,'9, 7, 6'],['Leg press',190,'10, 10, 10'],['Barbell overhead press',80,'8, 7'],['Stiff-leg deadlift',135,'8, 8, 8'],['Seated flies',145,'8, 8, 8']]},
  {date:'2026-07-02', exercises:[['Assisted pull-ups',37.5,'8, 8, 8'],['Cable chest press',160,'10, 10, 10'],['Split squats',30,'8, 8, 8'],['Seated rows',125,'10, 10, 7'],['Dumbbell overhead press',35,'10, 7, 6'],['Stiff-leg deadlift',125,'8, 8, 8']]},
  {date:'2026-06-27', exercises:[['Bench press',125,'8, 8, 8'],['Barbell squats',145,'10, 10, 10'],['Barbell overhead press',80,'8, 7, 4'],['Cable single-arm row',95,'10, 10, 10'],['Seated flies',140,'10, 10, 10'],['Tricep cable pulldown',39,'10, 10, 10']]},
  {date:'2026-06-22', exercises:[['Assisted pull-ups',44,'10, 10, 8'],['Barbell squats',145,'8, 8, 8'],['Barbell overhead press',75,'10, 10, 8'],['Stiff-leg deadlift',105,'10, 10, 10'],['Hip abductors',180,'10, 10, 10'],['Seated flies',135,'10, 10, 10']]},
  {date:'2026-06-17', exercises:[['Bench press',120,'10, 10, 10'],['Elevated split squats',30,'8, 8, 8'],['Seated rows',125,'10, 10, 8'],['Cable flies',160,'10, 10, 10'],['Triceps pulldown',39,'10, 10, 10']]},
  {date:'2026-06-15', exercises:[['Assisted pull-ups',44,'8, 8, 8'],['Barbell overhead press',70,'10, 10, 10'],['Lat pulldown',115,'10, 10, 10'],['Cable single-arm row',90,'10, 10, 10'],['Incline dumbbell chest press',40,'10, 9, 8'],['Leg press',185,'10, 10, 10']]},
  {date:'2026-06-12', exercises:[['Assisted pull-ups',50,'10, 10, 10'],['Bench press',120,'8, 8, 8'],['Squats',140,'10, 10, 10'],['Dumbbell overhead press',35,'10, 10, 7'],['Seated flies',130,'10, 10, 10'],['Seated rows',125,'10, 8, 8']]},
  {date:'2026-06-10', exercises:[['Assisted pull-ups',50,'10, 10, 9'],['Barbell overhead press',70,'10, 10, 7'],['Leg press',180,'10, 10, 10'],['Cable flies',120,'12, 12, 12'],['Elevated split squats',25,'8, 8, 8'],['Triceps pulldown',37.5,'10, 10, 10']]},
  {date:'2026-06-08', exercises:[['Assisted pull-ups',50,'8, 8, 8'],['Bench press',120,'8, 7, 6'],['Squats',135,'10, 10, 10'],['Dumbbell overhead press',35,'10, 9, 7'],['Seated rows',125,'10, 8, 8'],['Incline dumbbell chest press',40,'9, 5']]}
].map((w, id) => ({ id: `seed-${id}`, ...w, exercises:w.exercises.map(([name, weight, reps])=>({name,weight,reps,unit:'lb',details:''})) }));

const storedWorkouts = JSON.parse(localStorage.getItem(STORAGE_KEY) || 'null');
let workouts = storedWorkouts || seedWorkouts;
// The imported notes live in the exact same local log as newly saved workouts.
if (!storedWorkouts) localStorage.setItem(STORAGE_KEY, JSON.stringify(workouts));
const $ = (selector) => document.querySelector(selector);
const sortWorkouts = () => [...workouts].sort((a,b) => b.date.localeCompare(a.date));
const dateLabel = date => new Intl.DateTimeFormat('en-CA',{weekday:'short',month:'short',day:'numeric',year:'numeric'}).format(new Date(`${date}T12:00:00`));
const save = () => localStorage.setItem(STORAGE_KEY, JSON.stringify(workouts));
const displayWeight = ex => ex.weight !== null && ex.weight !== '' ? `${ex.weight} ${ex.unit || 'lb'}` : '';

function render() {
  const ordered = sortWorkouts(); const latest = ordered[0];
  const exerciseCount = workouts.reduce((sum,w)=>sum+w.exercises.length,0);
  $('#stats-grid').innerHTML = `<div class="stat"><p class="eyebrow">SESSIONS</p><strong>${workouts.length}</strong><span>logged</span></div><div class="stat"><p class="eyebrow">LIFTS</p><strong>${exerciseCount}</strong><span>total entries</span></div><div class="stat"><p class="eyebrow">LAST</p><strong>${latest ? new Date(`${latest.date}T12:00`).toLocaleDateString('en-CA',{month:'short',day:'numeric'}) : '—'}</strong><span>session</span></div>`;
  $('#last-workout-copy').textContent = latest ? `Last session: ${dateLabel(latest.date)} · ${latest.exercises.length} exercises.` : 'Log today’s lifts and keep your momentum moving.';
  const cards = ordered.map(workoutCard).join(''); $('#all-workouts').innerHTML = cards || '<p class="subtle">No workouts yet.</p>'; $('#recent-workouts').innerHTML = ordered.slice(0,3).map(workoutCard).join('');
  const names = [...new Set(workouts.flatMap(w=>w.exercises.map(e=>e.name)))].sort();
  $('#exercise-library').innerHTML = names.map(name => `<div class="workout-card"><h3>${escapeHtml(name)}</h3><p class="exercise-summary">${workouts.filter(w=>w.exercises.some(e=>e.name===name)).length} sessions logged</p></div>`).join('');
  $('#exercise-suggestions').innerHTML = names.map(n=>`<option value="${escapeHtml(n)}"></option>`).join('');
}
function workoutCard(w) { const summary = w.exercises.slice(0,3).map(e=>`${e.name}${e.weight !== null ? ` · ${displayWeight(e)}` : ''}`).join('  ·  '); return `<button class="workout-card" data-workout-id="${w.id}"><div class="workout-card-top"><div><time>${dateLabel(w.date)}</time><h3>${w.note ? escapeHtml(w.note) : `${w.exercises.length} exercise${w.exercises.length===1?'':'s'}`}</h3></div><span class="pill">${w.exercises.length} lifts</span></div><p class="exercise-summary">${escapeHtml(summary)}${w.exercises.length>3?'…':''}</p></button>`; }
function escapeHtml(value) { return String(value || '').replace(/[&<>'"]/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c])); }
function lastLoggedExercise(name) { const key=name.trim().toLowerCase(); if (!key) return null; return sortWorkouts().flatMap(w=>w.exercises.map(ex=>({...ex,date:w.date}))).find(ex=>ex.name.toLowerCase()===key) || null; }
function applyPreviousExercise(article) { const nameInput=article.querySelector('.exercise-name'); const previous=lastLoggedExercise(nameInput.value); const hint=article.querySelector('.last-time'); if (!previous) { hint.textContent=''; return; } article.querySelector('.exercise-weight').value=previous.weight ?? ''; article.querySelector('.exercise-unit').value=previous.unit||'lb'; article.querySelector('.exercise-reps').value=previous.reps||''; article.querySelector('.exercise-details').value=previous.details||''; hint.textContent=`Last time (${dateLabel(previous.date)}): ${displayWeight(previous) || 'no weight'} × ${previous.reps}`; }
function addExercise(data={}) { const node = $('#exercise-template').content.cloneNode(true); const article = node.querySelector('.exercise-entry'); article.querySelector('.exercise-name').value=data.name||''; article.querySelector('.exercise-weight').value=data.weight ?? ''; article.querySelector('.exercise-unit').value=data.unit||'lb'; article.querySelector('.exercise-reps').value=data.reps||''; article.querySelector('.exercise-details').value=data.details||''; article.querySelector('.remove-exercise').onclick=()=>article.remove(); article.querySelector('.exercise-name').addEventListener('change',()=>applyPreviousExercise(article)); article.querySelector('.exercise-name').addEventListener('blur',()=>applyPreviousExercise(article)); $('#exercise-entries').append(node); }
function openWorkout() { $('#workout-date').value = new Date().toISOString().slice(0,10); $('#workout-note').value=''; $('#exercise-entries').innerHTML=''; addExercise(); $('#workout-dialog').showModal(); }
function openWorkoutDetail(id) { const workout=workouts.find(w=>w.id===id); if (!workout) return; $('#detail-title').textContent=workout.note || `${workout.exercises.length} exercise${workout.exercises.length===1?'':'s'}`; $('#detail-date').textContent=dateLabel(workout.date); $('#detail-exercises').innerHTML=workout.exercises.map(ex=>`<article class="exercise-entry detail-exercise"><h3>${escapeHtml(ex.name)}</h3><p><strong>${displayWeight(ex) || 'Bodyweight'}</strong> · ${escapeHtml(ex.reps)} reps</p>${ex.details ? `<p>${escapeHtml(ex.details)}</p>` : ''}</article>`).join(''); $('#workout-detail-dialog').showModal(); }

$('#new-workout').onclick=openWorkout; $('#start-workout').onclick=openWorkout; $('#close-dialog').onclick=()=>$('#workout-dialog').close(); $('#add-exercise').onclick=()=>addExercise();
$('#close-detail-dialog').onclick=()=>$('#workout-detail-dialog').close();
document.addEventListener('click', event => { const card=event.target.closest('[data-workout-id]'); if (card) openWorkoutDetail(card.dataset.workoutId); });
document.querySelectorAll('[data-view]').forEach(button=>button.addEventListener('click',()=>{ const view=button.dataset.view; document.querySelectorAll('.view').forEach(v=>v.classList.toggle('active',v.id===view)); document.querySelectorAll('.nav-item').forEach(v=>v.classList.toggle('active',v.dataset.view===view)); window.scrollTo({top:0,behavior:'smooth'}); }));
$('#workout-form').addEventListener('submit', event => { event.preventDefault(); const exercises=[...document.querySelectorAll('.exercise-entry')].map(entry=>({name:entry.querySelector('.exercise-name').value.trim(),weight:entry.querySelector('.exercise-weight').value === '' ? null : Number(entry.querySelector('.exercise-weight').value),unit:entry.querySelector('.exercise-unit').value,reps:entry.querySelector('.exercise-reps').value.trim(),details:entry.querySelector('.exercise-details').value.trim()})).filter(e=>e.name&&e.reps); if(!exercises.length) return; workouts.push({id:crypto.randomUUID(),date:$('#workout-date').value,note:$('#workout-note').value.trim(),exercises}); save(); render(); $('#workout-dialog').close(); });
render();
